services:
  db:
    container_name: "crm-DDD-dev-database"
    image: "postgres:18-alpine"
    restart: "no"
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "crm_DDD_postgres"
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql"

volumes:
  postgres_data: